stages:
    - compile
    - test

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_STRATEGY: fetch

try_compiling:
    stage: compile
    artifacts:
        paths:
            - build
        expire_in: 30 minutes

    script:
        - mkdir -p build
        - cd build
        - cmake ..
          #        - make cudd # needs to be build separately (dunno why)
        - make all

# cpp check is put in a separate script file as we want to perform stuff that
# fits this yaml style rather badly
run_cppcheck:
    stage: compile # no need to wait for the actual compilation
    script:
        - ./stylecheck.sh

run_tests:
    stage: test
    script:
        - cd build/tests
          # the leading dot seems to be necessary
        - ./error_metrics_test
        - ./operations_test
        - ./parsing_test
