stages:
    - compile
    - test

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_STRATEGY: fetch


.ciconf:
    only:
        variables:
            - $CI_PROJECT_NAMESPACE == "keszocze"

try_compiling:
    extends: .ciconf
    stage: compile
    artifacts:
        paths:
            - build
        expire_in: 30 minutes

    script:
        - date
        - mkdir -p build/bw_output
        - cd build
        - cmake ..
          #        - make cudd # needs to be build separately (dunno why)
        - /opt/sonar-build-wrapper/build-wrapper-linux-x86-64 --out-dir bw_output make all
        - date

# cpp check is put in a separate script file as we want to perform stuff that
# fits this yaml style rather badly
run_cppcheck:
    extends: ciconf
    stage: compile # no need to wait for the actual compilation
    script:
        - date
        - ./stylecheck.sh
        - date

run_sonarqube:
    extends: .ciconf
    stage: test # we have to wait for new data to be present in bw_output
    script: 
        - /opt/sonar-scanner/bin/sonar-scanner

run_tests:
    stage: test
    script:
        - cd build/tests
          # the leading dot seems to be necessary
        - ./error_metrics_test
        - ./operations_test
        - ./parsing_test
