stages:
    - compile
    - test

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_STRATEGY: fetch


.ciconf:
    only:
        variables:
            - $CI_PROJECT_NAMESPACE == "keszocze"


compile_with_gcc:
    extends: .ciconf
    stage: compile
    artifacts:
        paths:
            - build/bw_output
            - build/tests
            - build/src
        expire_in: 30 minutes
    script:
        - mkdir -p build/bw_output
        - cd build
        - cmake ..
        - /opt/sonar-build-wrapper/build-wrapper-linux-x86-64 --out-dir bw_output make -j 4 all

compile_with_clang:
    extends: .ciconf
    stage: compile
    script: 
        - mkdir build
        - cd build
        - cmake -DCMAKE_CXX_COMPILER=clang++ ..
        - make -j 4 all

# cpp check is put in a separate script file as we want to perform stuff that
# fits this yaml style rather badly
run_cppcheck:
    extends: .ciconf
    stage: compile # no need to wait for the actual compilation
    script:
        - ./stylecheck.sh

run_sonarqube:
    extends: .ciconf
    stage: test # we have to wait for new data to be present in bw_output
    script: 
        - /opt/sonar-scanner/bin/sonar-scanner

run_tests:
    extends: .ciconf
    stage: test
    script:
        - cd build/tests
        - "for filename in *_test; do echo \"Running Test: $filename\"; ./$filename; done"
