stages:
    - compile
    - test
    - quality

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_STRATEGY: fetch


.ciconf:
    only:
        variables:
            - $CI_PROJECT_NAMESPACE == "keszocze"

try_compiling:
    extends: .ciconf
    stage: compile
    artifacts:
        paths:
            - build
        expire_in: 30 minutes

    script:
        - mkdir -p build/bw_output
        - cd build
        - cmake ..
        - make -j 4 cudd # needs to be build separately (dunno why)
        - /opt/sonar-build-wrapper/build-wrapper-linux-x86-64 --out-dir bw_output make -j 4 all

# cpp check is put in a separate script file as we want to perform stuff that
# fits this yaml style rather badly
run_cppcheck:
    extends: .ciconf
    stage: quality # no need to wait for the actual compilation
    script:
        - ./stylecheck.sh

run_sonarqube:
    extends: .ciconf
    stage: quality
    script: 
        - /opt/sonar-scanner/bin/sonar-scanner

run_tests:
    extends: .ciconf
    stage: test
    script:
        - cd build/tests
          # the leading dot seems to be necessary
        - find -name '*_test' -exec {} \;
        - rm -rf coverage
        - mkdir coverage
        - /opt/software/usr/local/bin/gcovr -r ../../ --object-directory CMakeFiles --sonarqube coverage/coverage.xml