before_script:
    - echo "Running CI job before script"

check-environment:
    script:
        - echo $(which cmake)
        - echo $(which g++)
        - echo $(which make)
        - echo $(which cppcheck) 
