name: main-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        sudo apt install libboost-serialization-dev libtbb-dev
        mkdir build
        cd build
        cmake -DBUILD_DOCUMENTATION=OFF ..
        make -j $(nproc)  
      
