name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install-dependencies:
    
    runs-on: ubuntu-latest
    steps:
    - name: install-dep
      run: |
        sudo apt install libboost-serialization-dev libtbb-dev
    
  build:

    runs-on: ubuntu-latest
    needs: install-dependencies
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        mkdir build
        cd build
        cmake ..
        make -j $(nproc)  
      
